cache-to = ["type=registry,ref=docker-registry.buildx.svc.cluster.local:5000/my-app:cache"]
cache-from = ["type=registry,ref=docker-registry.buildx.svc.cluster.local:5000/my-app:cache"]

#cache-to = ["type=local,dest=/tmp/cache,mode=max"]
#cache-from = ["type=local,src=/tmp/cache,mode=max"]
